### ISSUE TITLE
Critical CSS not being included in production builds

### ISSUE THREAD

**Issue by nathom** [schnerring/hugo-theme-gruvbox#161]
I have a custom css file with the path `assets/css/critical/01_giscus.css`. When running Hugo as a server, it is included in the HTML, but when running `hugo` by itself for production builds it is not included. 

I know this because when I run `hugo server --renderToDisk` I can view the generated files in `public` and see that the CSS is there. I also set `relativeURLs = true` in Hugo.toml with no effect. Not sure if I'm doing something wrong or if it's a bug.

**Comment by schnerring** [comment]
It probably has to do with the PostCSS plugins which are executed in production:

https://github.com/schnerring/hugo-theme-gruvbox/blob/main/postcss.config.js#L24-L34

Specifically, PurgeCSS removes unused CSS. Have a look at the [PurgeCSS Safelisting docs](https://purgecss.com/safelisting.html). Let me know how it goes!

I should probably mention this in the docs. 🤔

**Comment by nathom** [comment]
Thank you. Putting `/* purgecss ignore */` above the rule fixed the issue

**Comment by davegallant** [comment]
I've also ran into this issue without adding any additional CSS. There's stock critical css missing in my production builds and the only way I can get the page to render nicely is to remove [this](https://github.com/davegallant/hugo-theme-gruvbox/commit/f31cb2b5c2f414b1ee704215cf02b0bde055f503).

I'm not sure if I'm missing something in the config. The css purging seems to be overly aggressive for production builds.

**Comment by schnerring** [comment]
Do you have a sample repo containing the issue? @davegallant

**Comment by davegallant** [comment]
> Do you have a sample repo containing the issue? @davegallant I can't reproduce the issue.

Yeah: https://github.com/davegallant/davegallant.github.io

Oddly, I also had to [remove the integrity checks](https://github.com/davegallant/hugo-theme-gruvbox/commit/90b486f98b8270d9fb2127ef0dc894af87ad1eb2) for the css and js for it to load correctly. I'm wondering now if it has something to do with the fact it's hosted on Cloudflare Pages.

**Comment by davegallant** [comment]
> Do you have a sample repo containing the issue? @davegallant I can't reproduce the issue.

Yeah: https://github.com/davegallant/davegallant.github.io

**Comment by schnerring** [comment]
And what CSS are you missing?

I checked out the commit `3f549f757687ffe090907e1624cee4342bd18bd9`, but I can't see any CSS files in `assets/css/` folder.

**Comment by davegallant** [comment]
> What CSS are you missing exactly?
> 
> I checked out the commit `3f549f757687ffe090907e1624cee4342bd18bd9`, but I can't see any CSS files in `assets/css/` folder.

Ah, that was before I pulled the theme in-tree. It's here:
https://github.com/davegallant/hugo-theme-gruvbox/tree/62aac1ea9f6d42dd735dc76d9d59771230ca6054/assets

**Comment by schnerring** [comment]
That's a fork of this theme, and a different repo alltogether.

Please provide clear steps to reproduce the issue, or provide a sample repo that I can simply `hugo server -e production`.

**Comment by davegallant** [comment]
> That's a fork of this theme, and a different repo alltogether.
> 
> Please provide clear steps to reproduce the issue, or provide a sample repo that I can simply `hugo server -e production`.
> 
> Also specify exactly what CSS you're missing in production.

Yes, there were previous commits before that were pointing to the non-forked repo in the go.mod. 

I should have documented this better at the time, but was able to repro again:
https://github.com/davegallant/hugo-theme-gruvbox-161/tree/main

**Comment by schnerring** [comment]
Okay, I reproduced the issue. You can achieve the same result by running:

```
cd example.com
hugo server -e production
```

**Comment by schnerring** [comment]
Well, the defaults inside the config of the theme are there for a reason. Why did you remove the following?

```
build:
  noJSConfigInAssets: true
  writeStats: true
```

Try adding that to your config.yaml.

**Comment by schnerring** [comment]
I'll add a comment to the config explaining that PurgeCSS requires `writeStats = true`. I'll also have to upgrade that setting, because it will be deprecated in future versions in favor of `buildStats`.

Also a question regarding user experience. Did the confusion maybe come from having the config split into multiple files under `config/_default/`? Would it make things easier for for time users if I consolidated these files?

**Comment by schnerring** [comment]
See https://github.com/schnerring/hugo-theme-gruvbox/commit/d3df58b1529a85702e68e588fefd640b6d7c5adf

Your config must include the following:

```toml
[build]
  [build.buildStats]
    # With each build, Hugo writes a hugo_stats.json file that contains arrays
    # of the class attributes, id attributes, and tags of each HTML element
    # within the published site. For production builds, this file is required
    # by PurgeCSS to prune unused CSS.
    enable = true
```

To debug PurgeCSS with `hugo server -e production`, also add the following Hugo mount:

```toml
[[module.mounts]]
  # Add hugo_stats.json to Hugo's server watcher
  # See https://gohugo.io/getting-started/configuration/#configure-cache-busters
  source = "hugo_stats.json"
  target = "assets/watching/hugo_stats.json"
```
