### ISSUE TITLE
Improve README.md for how to enable search

### ISSUE THREAD

**Issue by stephenjayakar** [schnerring/hugo-theme-gruvbox#304]
I initially was going to make a post about how search doesn't work out of the box, and I couldn't figure out how to fix it. However, after looking at your [actual website](https://github.com/schnerring/schnerring.github.io/blob/main/config/_default/config.toml), I found this block that ended up fixing search.

```toml
[outputs]
  home = ["html", "searchIndex"]

[outputFormats]
  [outputFormats.searchIndex]
    mediaType = "application/json"
    baseName = "search-index"
    isPlainText = true
    notAlternative = true
```

I'm new to `hugo` so it's possible this was obvious to you, but it would be really helpful to add this to your README
